Revert "config-tools: extract CPU frequency info in board_inspector"
This reverts commit 635120e3f2fb40e769bdeebed36f33eb8fd17440.

to fix acrn over qemu

Traceback (most recent call last):
  File "/mnt/acrn/acrn-hypervisor/build/acrn_board_inspector_deb/bin/board_inspector.py", line 248, in <module>
    main(args.board_name, board_xml, args)
  File "/mnt/acrn/acrn-hypervisor/build/acrn_board_inspector_deb/bin/board_inspector.py", line 194, in main
    module.extract(args, board_etree)
  File "/mnt/acrn/acrn-hypervisor/build/acrn_board_inspector_deb/bin/extractors/10-processors.py", line 175, in extract
    extract_topology(processors_node)
  File "/mnt/acrn/acrn-hypervisor/build/acrn_board_inspector_deb/bin/extractors/10-processors.py", line 129, in extract_topology
    extract_model(processors_node, cpu_id, family_id, model_id, core_type, native_model_id)
  File "/mnt/acrn/acrn-hypervisor/build/acrn_board_inspector_deb/bin/extractors/10-processors.py", line 76, in extract_model
    msr_data = msr_reg.rdmsr(cpu_id)
  File "/mnt/acrn/acrn-hypervisor/build/acrn_board_inspector_deb/bin/cpuparser/platformbase.py", line 144, in rdmsr
    r = msr_reader.read(8)
OSError: [Errno 5] Input/output error